import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import { discoverPlugins, flattenTools } from '../bridge/loader.js';
import { defaultValidators } from '../loop/validators.js';
import { selfCritique } from '../loop/critic.js';
import { buildRelationGraph, type RelationEdge } from '../graph/relations.js';

/**
 * RSI (recursive self-improvement) engine.
 *
 * Loop:  observe catalog -> propose candidates from relation graph
 *        -> materialize plugin source -> compile -> execute sample inputs
 *        -> score with L3 validators + critique -> keep fittest -> record lineage
 *
 * Everything is deterministic given the same catalog, so runs are reproducible.
 */

export interface Candidate {
  id: string;
  name: string;
  description: string;
  members: string[];
  source: string;
}

export interface Evaluation {
  id: string;
  compiled: boolean;
  executed: boolean;
  score: number;
  validatorFailures: string[];
  notes: string[];
}

export interface Lineage {
  generation: number;
  startedAt: string;
  embedder: string;
  candidates: number;
  kept: string[];
  rejected: string[];
  evaluations: Evaluation[];
}

const SAMPLE_BY_TOOL: Record<string, string> = {
  'dsh-tool-text-summary.summarize': 'top=2\n第一句用于摘要测试。第二句包含数字 42。',
  'dsh-tool-json-format.format': '{"rsi":true,"n":1}',
  'dsh-tool-unit-convert.convert': '{"value":10,"from":"km","to":"mile"}',
  'dsh-tool-codec-kit.codec': '{"action":"encode","encoding":"base64","text":"rsi"}',
  'dsh-tool-text-diff.diff': '{"a":"alpha beta","b":"alpha gamma"}',
  'dsh-tool-date-math.calc': '{"start":"2026-01-05","addDays":7}',
  'dsh-tool-csv-stats.stats': 'a,b\n1,2\n3,4',
  'dsh-tool-loan-calc.calc': '{"principal":100000,"annualRatePct":3,"years":5}',
};

/** Propose pipeline candidates by composing tools connected in the relation graph. */
export function proposeCandidates(
  edges: RelationEdge[],
  available: string[],
  limit = 3,
): Candidate[] {
  const have = new Set(available);
  const out: Candidate[] = [];
  const seen = new Set<string>();

  for (const e of edges.sort((a, b) => b.score - a.score)) {
    if (!have.has(e.source) || !have.has(e.target)) continue;
    if (e.source === e.target) continue;
    const key = [e.source, e.target].sort().join('+');
    if (seen.has(key)) continue;
    seen.add(key);

    const slug = key
      .replace(/^dsh-tool-/, '')
      .replace(/\./g, '-')
      .replace(/\+/g, '-x-')
      .slice(0, 48);
    const name = `dsh-tool-rsi-${slug}`;
    out.push({
      id: key,
      name,
      description: `RSI-composed pipeline (${e.predicate}): ${e.source} -> ${e.target}`,
      members: [e.source, e.target],
      source: renderPipelineSource(name, e.predicate, e.source, e.target),
    });    if (out.length >= limit) break;
  }
  return out;
}

function renderPipelineSource(
  name: string,
  predicate: string,
  a: string,
  b: string,
): string {
  const [aPlugin, aTool] = a.split('.');
  const [bPlugin, bTool] = b.split('.');
  return `// Generated by DSH RSI engine - self-sufficient pipeline (${predicate})
// ${a} -> ${b}
const STAGE_A = '${a}';
const STAGE_B = '${b}';
const STAGE_A_DIR = '${aPlugin}';
const STAGE_A_TOOL = '${aTool}';
const STAGE_B_DIR = '${bPlugin}';
const STAGE_B_TOOL = '${bTool}';

async function loadHandler(dir: string, tool: string) {
  const mod: any = await import(\`../../\${dir}/src/index.js\`);
  const plugin = mod.default ?? mod;
  const reg: Record<string, (i: string) => Promise<string>> = {};
  await plugin.apply({
    defineTool: (d: any) => { reg[d.name] = d.handler; },
    logger: { info() {}, warn() {} },
  });
  return reg[tool];
}

export default {
  async apply(ctx: PluginContext) {
    ctx.defineTool({
      name: 'pipeline',
      description:
        'RSI pipeline: runs ${a} then ${b}. Input JSON passed to stage A.',
      handler: async (inputData: string) => {
        try {
          const runA = await loadHandler(STAGE_A_DIR, STAGE_A_TOOL);
          const runB = await loadHandler(STAGE_B_DIR, STAGE_B_TOOL);
          const stageA = await runA(inputData);
          const stageB = await runB(stageA);
          return [
            '# RSI 组合管道结果',
            '',
            \`- 谓词：${predicate}\`,
            \`- 阶段 A（\${STAGE_A}）输出长度：\${stageA.length}\`,
            '',
            '## 阶段 A 输出',
            stageA,
            '',
            '## 阶段 B 输出',
            stageB,
            '',
            '> 免责声明：本输出由 RSI 自动组合的确定性管道生成，仅供参考。',
          ].join('\\n');
        } catch (e) {
          return [
            '# RSI 管道执行失败',
            '',
            String(e),
            '',
            \`- 阶段 A：\${STAGE_A}\`,
            \`- 阶段 B：\${STAGE_B}\`,
            '',
            '> 免责声明：本输出由 RSI 引擎生成，仅供参考。',
          ].join('\\n');
        }
      },
    });
  },
};
`;
}

export interface RsiOptions {
  generations?: number;
  keep?: number;
  workDir?: string;
  limitCandidates?: number;
}

export async function runRsi(opts: RsiOptions = {}): Promise<Lineage[]> {
  const generations = opts.generations ?? 1;
  const keep = opts.keep ?? 2;
  const workDir = opts.workDir ?? process.cwd();
  const limitCandidates = opts.limitCandidates ?? 3;
  const history: Lineage[] = [];

  for (let gen = 1; gen <= generations; gen++) {
    const startedAt = new Date().toISOString();
    const graph = await buildRelationGraph();
    const { plugins } = await discoverPlugins();
    const available = flattenTools(plugins).map((t) => t.fqName);

    const candidates = proposeCandidates(graph.edges, available, limitCandidates);
    const evaluations: Evaluation[] = [];

    // Materialize candidates as plugin dirs, then compile once.
    const staged: Candidate[] = [];
    for (const c of candidates) {
      const dir = path.join(workDir, 'plugins', c.name, 'src');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(workDir, 'plugins', c.name, 'cordis.yml'),
        [
          `name: ${c.name}`,
          'version: 0.1.0',
          `description: ${c.description}`,
          'public: true',
          'tools:',
          `  - pipeline`,
          '',
        ].join('\n'),
      );
      fs.writeFileSync(path.join(dir, 'index.ts'), c.source);
      staged.push(c);
    }

    let compiled = false;
    try {
      execSync('npx tsc -p tsconfig.plugins.json', { cwd: workDir, stdio: 'pipe' });
      compiled = true;
    } catch {
      compiled = false;
    }

    for (const c of staged) {
      const ev: Evaluation = {
        id: c.id,
        compiled,
        executed: false,
        score: 0,
        validatorFailures: [],
        notes: [],
      };
      if (compiled) {
        const out = await tryExecute(workDir, c, available);
        if (out !== null) {
          ev.executed = true;
          const failed = defaultValidators().map((v) => v(out)).filter((r) => !r.passed);
          ev.validatorFailures = failed.map((f) => f.validator);
          ev.score = Number(
            Math.max(0, selfCritique(out).overall - failed.length * 0.1).toFixed(3),
          );
          ev.notes.push(`output length ${out.length}`);
        }
      }
      evaluations.push(ev);
    }

    evaluations.sort((a, b) => b.score - a.score);
    const kept = evaluations.slice(0, keep).map((e) => e.id);
    const rejected = evaluations.slice(keep).map((e) => e.id);

    // Remove rejected plugin dirs (evolution: only survivors persist)
    for (const c of staged) {
      if (!kept.includes(c.id)) {
        fs.rmSync(path.join(workDir, 'plugins', c.name), { recursive: true, force: true });
      }
    }

    const lineage: Lineage = {
      generation: gen,
      startedAt,
      embedder: graph.embedder,
      candidates: candidates.length,
      kept,
      rejected,
      evaluations,
    };
    history.push(lineage);

    const dir = path.join(workDir, 'rsi');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, 'lineage.json'),
      JSON.stringify(history, null, 2) + '\n',
    );
  }

  return history;
}

async function tryExecute(
  workDir: string,
  c: Candidate,
  available: string[],
): Promise<string | null> {
  try {
    const { discoverPlugins: rediscover, flattenTools: flat } = await import(
      '../bridge/loader.js'
    );
    const { plugins } = await rediscover();
    const tools = flat(plugins);
    const self = tools.find((t) => t.plugin === c.name);
    if (!self?.handler) return null;

    // bridge stage A/B to real handlers so the pipeline actually runs
    const bridge = async (fq: string, input: string): Promise<string> => {
      const t = tools.find((x) => x.fqName === fq);
      if (!t?.handler) return `[missing ${fq}]`;
      return t.handler(input);
    };
    (globalThis as any).__dshPipelineBridge = bridge;

    const sample = SAMPLE_BY_TOOL[c.members[0]!] ?? c.members[0]!;
    const out = await self.handler(sample);
    delete (globalThis as any).__dshPipelineBridge;
    void workDir;
    void available;
    return out;
  } catch {
    return null;
  }
}
