// Generated by DSH RSI harvester - generic probe adapter for "csv-parser"
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

export default {
  async apply(ctx: PluginContext) {
    ctx.defineTool({
      name: 'probe',
      description: "Introspect external package csv-parser: list exports and invoke the default export when callable.",
      handler: async (inputData: string) => {
        try {
          const mod: any = require("csv-parser");
          const keys = Object.keys(mod ?? {});
          const kinds = keys.slice(0, 40).map((k) => {
            const t = typeof mod[k];
            return `| \`${k}\` | ${t} |`;
          });
          const lines = [
            '# 外部包能力探针',
            '',
            `- 包：csv-parser`,
            `- 导出成员：${keys.length}`,
            '',
            '| 导出 | 类型 |',
            '|---|---|',
            ...kinds,
          ];
          const callable =
            typeof mod === 'function'
              ? mod
              : typeof mod.default === 'function'
                ? mod.default
                : null;
          if (callable) {
            try {
              const out = await callable(inputData);
              lines.push(
                '',
                '## 默认导出调用结果',
                '',
                '```',
                typeof out === 'string' ? out.slice(0, 2000) : JSON.stringify(out, null, 2).slice(0, 2000),
                '```',
              );
            } catch (e) {
              lines.push('', `## 默认导出调用失败`, '', String(e));
            }
          } else {
            lines.push(
              '',
              '## 说明',
              '该包没有可直接调用的默认导出，需为其编写专用配方（recipe）后才能作为独立工具使用。',
            );
          }
          lines.push('', '> 免责声明：探针结果来自运行时自省，仅供参考。');
          return lines.join('\n');
        } catch (e) {
          return [
            '# 外部包探针失败',
            '',
            `- 包：csv-parser`,
            `- 错误：${String(e)}`,
            '',
            '> 免责声明：本工具包装第三方库，仅供参考。',
          ].join('\n');
        }
      },
    });
  },
};
