// Generated by DSH RSI harvester - adapter for external package "validator"
// Recipe: Validate email / URL / mobile number strings (validator, MIT).
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

export default {
  async apply(ctx: PluginContext) {
    ctx.defineTool({
      name: 'check',
      description: "Validate email / URL / mobile number strings (validator, MIT). Input: user@example.com",
      handler: async (inputData: string) => {
        try {
          const mod: any = require("validator");
          const v = mod.default ?? mod;
        const s = inputData.trim();
        const checks: [string, boolean][] = [
          ['email', v.isEmail ? v.isEmail(s) : false],
          ['url', v.isURL ? v.isURL(s, { require_protocol: false }) : false],
          ['手机号(zh-CN)', v.isMobilePhone ? v.isMobilePhone(s, 'zh-CN') : false],
          ['纯数字', /^\d+$/.test(s)],
        ];
        return ['# 格式校验', '', `- 输入：\`${s}\``, '', '| 规则 | 结果 |', '|---|---|', ...checks.map(([k, ok]) => `| ${k} | ${ok ? 'PASS' : 'FAIL'} |`), '', '> 免责声明：基于第三方库的静态校验，仅供参考。'].join('\n');
        } catch (e) {
          return [
            '# 外部适配器执行失败',
            '',
            `- 包：validator`,
            `- 错误：${String(e)}`,
            '',
            '> 免责声明：本工具包装第三方库，仅供参考。',
          ].join('\n');
        }
      },
    });
  },
};
