// Generated by DSH RSI engine - self-sufficient pipeline (feeds_into)
// dsh-tool-invoice-calc.calc -> dsh-tool-loan-calc.calc
const STAGE_A = 'dsh-tool-invoice-calc.calc';
const STAGE_B = 'dsh-tool-loan-calc.calc';
const STAGE_A_DIR = 'dsh-tool-invoice-calc';
const STAGE_A_TOOL = 'calc';
const STAGE_B_DIR = 'dsh-tool-loan-calc';
const STAGE_B_TOOL = 'calc';

async function loadHandler(dir: string, tool: string) {
  const mod: any = await import(`../../${dir}/src/index.js`);
  const plugin = mod.default ?? mod;
  const reg: Record<string, (i: string) => Promise<string>> = {};
  await plugin.apply({
    defineTool: (d: any) => { reg[d.name] = d.handler; },
    logger: { info() {}, warn() {} },
  });
  return reg[tool];
}

export default {
  async apply(ctx: PluginContext) {
    ctx.defineTool({
      name: 'pipeline',
      description:
        'RSI pipeline: runs dsh-tool-invoice-calc.calc then dsh-tool-loan-calc.calc. Input JSON passed to stage A.',
      handler: async (inputData: string) => {
        try {
          const runA = await loadHandler(STAGE_A_DIR, STAGE_A_TOOL);
          const runB = await loadHandler(STAGE_B_DIR, STAGE_B_TOOL);
          const stageA = await runA(inputData);
          const stageB = await runB(stageA);
          return [
            '# RSI 组合管道结果',
            '',
            `- 谓词：feeds_into`,
            `- 阶段 A（${STAGE_A}）输出长度：${stageA.length}`,
            '',
            '## 阶段 A 输出',
            stageA,
            '',
            '## 阶段 B 输出',
            stageB,
            '',
            '> 免责声明：本输出由 RSI 自动组合的确定性管道生成，仅供参考。',
          ].join('\n');
        } catch (e) {
          return [
            '# RSI 管道执行失败',
            '',
            String(e),
            '',
            `- 阶段 A：${STAGE_A}`,
            `- 阶段 B：${STAGE_B}`,
            '',
            '> 免责声明：本输出由 RSI 引擎生成，仅供参考。',
          ].join('\n');
        }
      },
    });
  },
};
