import * as fs from 'node:fs';
import * as path from 'node:path';
import { readCordis, pluginsRoot } from './bridge/scanner.js';

/**
 * Produces a publish-ready Koishi/cordis marketplace package:
 *   - name must match koishi-plugin-*
 *   - peerDependencies must include koishi
 *   - `koishi` metadata field with localized description
 */
export function packKoishi(
  dirName: string,
  outRoot = 'publish',
): string {
  const meta = readCordis(dirName);
  if (!meta) throw new Error(`No cordis.yml for ${dirName}`);

  const pkgName = `koishi-plugin-${dirName.replace(/^dsh-tool-/, 'dsh-')}`;
  const outDir = path.resolve(process.cwd(), outRoot, dirName);
  const libDir = path.join(outDir, 'lib');
  fs.mkdirSync(libDir, { recursive: true });

  const compiled = path.join('dist', 'plugins', dirName, 'src');
  if (!fs.existsSync(compiled)) {
    throw new Error(`Plugin not built yet: run npm run build first (${compiled})`);
  }
  for (const f of fs.readdirSync(compiled)) {
    if (f.endsWith('.js')) fs.copyFileSync(path.join(compiled, f), path.join(libDir, f));
  }

  const pkg = {
    name: pkgName,
    version: meta.version,
    description: meta.description,
    contributors: [],
    license: 'MIT',
    type: 'commonjs',
    main: 'lib/index.js',
    files: ['lib'],
    keywords: ['chatbot', 'koishi', 'dsh', ...[dirName]],
    peerDependencies: { koishi: '^4.18.0' },
    koishi: {
      description: {
        en: meta.description,
        zh: meta.description,
      },
      public: meta.public ?? true,
      service: { required: [], optional: [], implements: [] },
    },
  };
  fs.writeFileSync(
    path.join(outDir, 'package.json'),
    JSON.stringify(pkg, null, 2) + '\n',
  );

  fs.writeFileSync(
    path.join(outDir, 'README.md'),
    [
      `# ${pkgName}`,
      '',
      meta.description,
      '',
      '> Generated by DSH Toolkit. Tool contract: `{ input_data: string }`.',
      '',
    ].join('\n'),
  );

  return outDir;
}

export function listPackable(): string[] {
  const root = pluginsRoot();
  if (!fs.existsSync(root)) return [];
  return fs
    .readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.startsWith('dsh-tool-'))
    .map((d) => d.name);
}
