// Generated by DSH RSI harvester - adapter for external package "papaparse"
// Recipe: Parse CSV text into JSON rows (papaparse, MIT).
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

export default {
  async apply(ctx: PluginContext) {
    ctx.defineTool({
      name: 'to_json',
      description: "Parse CSV text into JSON rows (papaparse, MIT). Input: name,age\nAlice,30\nBob,25",
      handler: async (inputData: string) => {
        try {
          const mod: any = require("papaparse");
          const Papa = mod.default ?? mod;
        const res = Papa.parse(inputData.trim(), { header: true, skipEmptyLines: true });
        const rows = res.data ?? [];
        return ['# CSV → JSON', '', `- 行数：${rows.length}`, '', '```json', JSON.stringify(rows.slice(0, 20), null, 2), '```', '', '> 免责声明：解析结果请自行校验，仅供参考。'].join('\n');
        } catch (e) {
          return [
            '# 外部适配器执行失败',
            '',
            `- 包：papaparse`,
            `- 错误：${String(e)}`,
            '',
            '> 免责声明：本工具包装第三方库，仅供参考。',
          ].join('\n');
        }
      },
    });
  },
};
